apps:
  - name: learn-nestjs
    script: ./dist/main.js
    exec_mode: 'cluster'
    instances: 4
    log_date_format: YYYY-MM-DD HH:mm:ss
    error_file: ./logs/error.log
    out_file: ./logs/out.log
